export enum CrudAction {
  ALL = "ALL",
  FIND_ALL = "FIND_ALL",
  FIND_BY_PK = "FIND_BY_PK",
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DESTROY = "DESTROY",
  ORDER = "ORDER",
  BULK_DESTROY = "BULK_DESTROY",
}
